apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-time-service
spec:
  selector:
    matchLabels:
      app: simple-time-service
  template:
    metadata:
      labels:
        app: simple-time-service
    spec:
      containers:
      - name: simple-time-service
        image: ghcr.io/ritika54/simple_time_service:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "1"
        ports:
        - containerPort: 8081
        imagePullPolicy: Always
      imagePullSecrets:
        - name: image-pull-secret