apiVersion: v1
kind: Service
metadata:
  name: simple-time-service
  namespace: simple-time-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-ritika-test"
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "172.191.136.5"
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  selector:
    app: simple-time-service
  ports:
  - port: 8081
    targetPort: 8081